Fitting models:   0%|          | 0/11 [00:00<?, ?it/s]Fitting models:   9%|▉         | 1/11 [00:00<00:02,  4.10it/s]Fitting models:  18%|█▊        | 2/11 [00:00<00:03,  2.94it/s]Fitting models:  27%|██▋       | 3/11 [00:01<00:03,  2.26it/s]Fitting models:  36%|███▋      | 4/11 [00:03<00:07,  1.03s/it]Fitting models:  45%|████▌     | 5/11 [00:04<00:07,  1.31s/it]Fitting models:  55%|█████▍    | 6/11 [00:05<00:04,  1.06it/s]Fitting models:  64%|██████▎   | 7/11 [00:06<00:04,  1.04s/it]Fitting models:  73%|███████▎  | 8/11 [00:20<00:15,  5.08s/it]Fitting models:  82%|████████▏ | 9/11 [00:30<00:13,  6.68s/it]Fitting models:  91%|█████████ | 10/11 [00:31<00:05,  5.02s/it]Fitting models: 100%|██████████| 11/11 [00:44<00:00,  7.54s/it]Fitting models: 100%|██████████| 11/11 [00:44<00:00,  4.08s/it]
Done:  J0323+0018
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:325: RuntimeWarning: invalid value encountered in scalar divide
  ea = abs(errors[2] / self.grad)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:326: RuntimeWarning: invalid value encountered in scalar divide
  eb = abs(errors[1] * (1.0 - eps) / self.grad)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:329: RuntimeWarning: invalid value encountered in scalar divide
  self.ellip_err = (abs(2.0 * errors[4] * (1.0 - eps) / self.sma
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:276: RuntimeWarning: invalid value encountered in scalar divide
  a = up_coeffs[1] / self.sma / abs(sample.gradient)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:277: RuntimeWarning: invalid value encountered in scalar divide
  b = up_coeffs[2] / self.sma / abs(sample.gradient)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:295: RuntimeWarning: invalid value encountered in scalar divide
  a_err = abs(a) * np.sqrt((ce[1] / up_coeffs[1])**2 + gre**2)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:296: RuntimeWarning: invalid value encountered in scalar divide
  b_err = abs(b) * np.sqrt((ce[2] / up_coeffs[2])**2 + gre**2)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:332: RuntimeWarning: invalid value encountered in scalar divide
  self.pa_err = (abs(2.0 * errors[3] * (1.0 - eps) / self.sma
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:276: RuntimeWarning: divide by zero encountered in scalar divide
  a = up_coeffs[1] / self.sma / abs(sample.gradient)
/home/insepien/miniconda3/envs/usc/lib/python3.11/site-packages/photutils/isophote/isophote.py:277: RuntimeWarning: divide by zero encountered in scalar divide
  b = up_coeffs[2] / self.sma / abs(sample.gradient)
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
ModelObjectWrapper: about to call _model.CreateModelImage()...
Done: J0323+0018
/home/insepien/dualAGN/fit/plot_fit_with1d.py:93: RuntimeWarning: divide by zero encountered in divide
  return -2.5*np.log10(intensity/area)+ magZPT
/home/insepien/dualAGN/fit/plot_fit_with1d.py:93: RuntimeWarning: invalid value encountered in log10
  return -2.5*np.log10(intensity/area)+ magZPT
/home/insepien/dualAGN/fit/plot_fit_with1d.py:93: RuntimeWarning: invalid value encountered in divide
  return -2.5*np.log10(intensity/area)+ magZPT
/home/insepien/dualAGN/fit/plot_fit_with1d.py:93: RuntimeWarning: divide by zero encountered in log10
  return -2.5*np.log10(intensity/area)+ magZPT
/home/insepien/dualAGN/fit/plot_fit_with1d.py:165: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  pdf.savefig(bbox_inches='tight', pad_inches=0.2);
/home/insepien/dualAGN/fit/plot_fit_with1d.py:53: UserWarning: All values for SymLogScale are below linthresh, making it effectively linear. You likely should lower the value of linthresh. 
  [fig.colorbar(im[i], ax=ax[i], shrink=0.5).ax.yaxis.set_major_formatter(FormatStrFormatter('%.2f')) for i in range(len(ax))]
/home/insepien/dualAGN/fit/plot_fit_with1d.py:118: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  fig = plt.figure(figsize=(14, 4),layout='tight')
Done:  J0323+0018
